version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/template_translator"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
